spring:
  datasource:
    url: jdbc:mysql://localhost:3306/adres?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 5959@Ssol
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create